name: "Jokkolabs Bamako"
title_en: "Jokkolabs Bamako — Coworking in Mali"
title_fr: "Jokkolabs Bamako — Coworking au Mali"

description_en: "Jokkolabs Bamako is the first co-working space in Mali. It is Open &amp; Sharing Oriented and part of the international Jokkolabs Network."
description_fr: "Jokkolabs Bamako est le premier espace de co-working au Mali. Il est orienté Partage et Ouverture et fait partie d'un mouvement international."

keywords_en: "co-working space bamako mali internet fast open free software knowledge"
keywords_fr: "co-working espace bamako mali internet rapide fast ouvert libre logiciel connaissance wikipedia free software knowledge"

url: "http://jokkolabs.ml"

paginate: 1
pagination_dir: blog
paginate_path: /blog/page:num

markdown: rdiscount
permalink: pretty
pygments: true
permalink: /blog/:year/:month/:day/:title