#!/bin/sh

# requires `slimit` bin: pip install slimit

#slimit < stylesheets/js/jquery.slides.min.js stylesheets/js/bootstrap.min.js stylesheets/js/waypoints.js stylesheets/js/jokkolabs.js > stylesheets/js/unified.js


## npm install collate


./minify.rb --force stylesheets/js/jquery-1.9.1.min.js stylesheets/js/jquery.slides.min.js stylesheets/js/bootstrap.min.js stylesheets/js/waypoints.js stylesheets/js/date.proto.js stylesheets/js/jokkolabs.js stylesheets/js/unified.js

lessc -x --yui-compress -O0 stylesheets/unified.less stylesheets/unified.css